
channels:
  - conda-forge
dependencies:
  # Required
  - python>=3.12
  - gdal==3.8.4
  - geopandas>=1.0.1
  - h3pandas>=0.2.6
  - rioxarray>=0.13.4
  - dask-geopandas>=0.4.1
  - pyarrow>=16.0.0
  - dask>=2024.8.0
  - click>=8.1.3
  - boto3>=1.26.85
  - tqdm>=4.66.5
  - click-log>=0.4.0
  - rasterio>=1.3.6
  - dask-expr>=1.1.2
  - numpy<2
  - pip
  - pip:
    # Use pip to install rhppandas from dev branch of git repo
    - git+https://github.com/manaakiwhenua/rHP-Pandas.git
    - git+https://github.com/manaakiwhenua/rhealpixdggs-py.git