
channels:
  - conda-forge
dependencies:
  # Required
  - python==3.11.5
  - gdal==3.6.4
  - geopandas>=0.12.2
  - h3pandas>=0.2.4
  - rioxarray>=0.13.4
  - dask-geopandas>=0.3.0
  - pyarrow>=14.0.1
  - dask>=2024.1.0
  - click>=8.1.3
  - boto3>=1.26.85
  - tqdm>=4.66.4
  - click-log>=0.4.0
  - rasterio>=1.3.6
  - dask-expr>=1.1.2
  - numpy<2
  - pip
  - pip:
    # Use pip to install rhppandas from dev branch of git repo
    - git+https://github.com/manaakiwhenua/rHP-Pandas.git@demaion/polyfill
    - git+https://github.com/manaakiwhenua/rhealpixdggs-py.git@demaion/polyfill